# Generated by Django 5.0.2 on 2024-06-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_download"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="filename",
            field=models.CharField(default="default_filename.mp3", max_length=255),
        ),
    ]
